version: "3"
services:
  inatel-database:
    image: mysql:8
    restart: always
    container_name: "inatel-database"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb
      - TZ=GMT
    ports:
      - 3306:3306
      - 33060:33060
    networks:
      - inatel-network

  acert-api:
    build: .
    container_name: "inatel-api"
    env_file:
      - docker-compose.env
    ports:
      - 8081:8081
    networks:
      - inatel-network
    depends_on:
      - inatel-database

networks:
  inatel-network:
    driver: bridge



