version: "3"
services:
  inatel-stocks-database:
    image: mysql:8
    restart: always
    container_name: "inatel-stocks-database"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb
      - TZ=GMT
    ports:
      - 3307:3306
      - 33061:33060
    networks:
      - inatel-network

  inatel-stock-api:
    build: .
    container_name: "inatel-stock-api"
    env_file:
      - docker-compose.env
    ports:
      - 8080:8080
    networks:
      - inatel-network
    depends_on:
      - inatel-stocks-database

networks:
  inatel-network:
   driver: bridge



